{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "0afe5189_2fc1d604",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 6
      },
      "lineNbr": 0,
      "author": {
        "id": 1392020
      },
      "writtenOn": "2022-02-17T17:53:37Z",
      "side": 1,
      "message": "Not sure if the failure on capture bot is caused by test. So do keep eye on it to see if test has a bug or not.",
      "revId": "0bbde50bd98422cdec38bd5534b0271f6087ecd2",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}