{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "1d8f8155_e4aeca5c",
        "filename": "/COMMIT_MSG",
        "patchSetId": 1
      },
      "lineNbr": 13,
      "author": {
        "id": 1329751
      },
      "writtenOn": "2021-09-08T17:54:50Z",
      "side": 1,
      "message": "ref",
      "range": {
        "startLine": 11,
        "startChar": 45,
        "endLine": 13,
        "endChar": 0
      },
      "revId": "8ade6464b46afb3841cf21f9e940dc0ae6a2d66c",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "7b763e94_b85cab76",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1256237
      },
      "writtenOn": "2021-09-08T17:50:05Z",
      "side": 1,
      "message": "How did the previous CL get through CQ?",
      "revId": "8ade6464b46afb3841cf21f9e940dc0ae6a2d66c",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "0d5f28cb_4de72e7e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1329751
      },
      "writtenOn": "2021-09-08T17:54:50Z",
      "side": 1,
      "message": "See commit message.. was not giving an error on the CQ.",
      "parentUuid": "7b763e94_b85cab76",
      "revId": "8ade6464b46afb3841cf21f9e940dc0ae6a2d66c",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "bc943026_7745b00f",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1256237
      },
      "writtenOn": "2021-09-08T18:27:04Z",
      "side": 1,
      "message": "More specifically, how did our trace test runs complete successfully if we weren\u0027t actually loading the trace shared objects?  I saw these ERR() vs. FAIL() in the review, but I presumed (wrongly) that something else would blow up if we couldn\u0027t even load the traces.\n\nI see now, we simply SKIPPED all tests, which is considered a PASS.",
      "parentUuid": "0d5f28cb_4de72e7e",
      "revId": "8ade6464b46afb3841cf21f9e940dc0ae6a2d66c",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "bb66d16b_f1be5ccb",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1329751
      },
      "writtenOn": "2021-09-08T18:35:50Z",
      "side": 1,
      "message": "Yeah, we just skipped them and didn\u0027t run them.",
      "parentUuid": "bc943026_7745b00f",
      "revId": "8ade6464b46afb3841cf21f9e940dc0ae6a2d66c",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}