{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "9e3acecb_49d153d2",
        "filename": "src/tests/restricted_traces/retrace_restricted_traces.py",
        "patchSetId": 3
      },
      "lineNbr": 465,
      "author": {
        "id": 1329751
      },
      "writtenOn": "2022-10-31T12:33:28Z",
      "side": 1,
      "message": "does this log the exception? if it doesn\u0027t please ensure the exception is logged.",
      "range": {
        "startLine": 465,
        "startChar": 16,
        "endLine": 465,
        "endChar": 25
      },
      "revId": "bcbe06fa3bce37221ca11d1e1f692122c7a2d753",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}